# select base image/os
FROM python:3

# set environment/os variable so Python prints things immediately
ENV PYTHONUNBUFFERED 1

# set working directory
WORKDIR /app

# copy over requirements.txt
COPY requirements.txt requirements.txt

# install dependencies
RUN pip install -r requirements.txt

#run Django dev server
CMD python attendees/account_info_consumer.py